"""Add email verification fields

Revision ID: 29555ae6b779
Revises: 28cc0a876d65
Create Date: 2025-04-30 13:24:15.643450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29555ae6b779'
down_revision = '28cc0a876d65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('verification_token', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('verification_token')
        batch_op.drop_column('email_verified')

    # ### end Alembic commands ###
