"""Add profile_picture and history_file columns

Revision ID: 6e475cecc218
Revises: 836f1f8c9438
Create Date: 2025-04-28 19:53:28.394273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e475cecc218'
down_revision = '836f1f8c9438'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('history_file', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('history_file')
        batch_op.drop_column('profile_picture')

    # ### end Alembic commands ###
